# action.yml
name: 'Git Diff Analyzer'
description: 'Assess the changes that have been made to be able to determine the level of impact of the changes. The Levenshtein distance is used to determine the level of impact.'
inputs:
  ld-threshold:  # id of input
    description: 'The maximum Levenshtein distance allowed for the changes to be considered as low impact'
    required: true
    default: '10'
  allowed-file-types:  # id of input
    description: 'The file types to be analyzed. Provide the extensions separated by whitespace. Example: "js html md". If other types of files are found, the level of impact will automatically be set to considerable.'
    required: true
    default: 'md'
outputs:
  impact-level: # id of output
    description: 'The level of impact of the changes. Can be low or considerable'
  max-ld-distance: # id of output
    description: 'The maximum Levenshtein distance found in the changes'
runs:
  using: 'docker'
  image: './src/Dockerfile'
  args:
    - ${{ inputs.ld-threshold }}
    - ${{ inputs.allowed-file-types }}
