on:
  pull_request:
    branches: [ main ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          ls -la
          git status
      # To use this repository's private action,
      # you must check out the repository
      - name: Diff Analyzer
        uses: ./ # Uses an action in the root directory
        id: diff-analyze
        with:
          ld-threshold: 8
          allowed-file-types: 'md'
          #git-base-ref: ${{ github.base_ref }}
      # Use the output from the previous step
      - name: Show the output
        run: echo "The change was impact-level ${{ steps.diff-analyze.outputs.impact-level }}"
